#!/bin/bash

#aspell -d en_GB -p ./gng.wordlist -t --dont-tex-check-comments --encoding="utf-8" -c <file>

# rule book components

for f in rules/{book,cam,cha,equ,mag,mon,npc,pri,rul,ski}*.tex
do
    aspell -d en_GB -p ./gng.wordlist \
        -t --dont-tex-check-comments \
        --encoding="utf-8" \
        --dont-backup \
        -c "${f}"
done



# adventures

for f in adventures/*/[0-9]*.tex
do
    aspell -d en_GB -p ./gng.wordlist \
        -t --dont-tex-check-comments \
        --encoding="utf-8" \
        --dont-backup \
        -c "${f}"
done



exit 0 # ---------------------
