#!/bin/bash

pdflatex book.tex
pdflatex book.tex
pdflatex book.tex

pdflatex intro.tex
pdflatex intro.tex
pdflatex intro.tex

#dvipdf book.dvi
#pdftex book.tex

#cp book.pdf ~/dl/"rules.`date +%y%m%d:%H%M`.pdf"
#cp book.pdf ~/dl/"rules.pdf"

rm *{.log,.aux,.toc,.dvi,.out}
#mv book.pdf ../

#aplay ~/doc/sound/softpop.wav

#okular ./book.pdf 1> /dev/null 2>&1 &
##okular ./book.pdf 1> /dev/null 2> /dev/null &
##okular ./book.pdf &> /dev/null &


